openapi: "3.0.2"

info:
  title: "Beacon Node API"
  description: "API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain."
  version: "0.11.1"
  contact:
    name: EF
    url: https://ethereum.org
    email: "dont-contact@ethereum.org"
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"

servers:
  - url: "{server_url}"
    variables:
      server_url:
        description: "Beacon node API url"
        default: "http://public-mainnet-node.ethereum.org/api"

tags:
  - name: Beacon
    description: Set of endpoints to query beacon chain.
  - name: MinimalValidatorApi
    description: The minimal set of endpoints to enable a working validator implementation.
  - name: Node
    description: APIs to query node related informations
  - name: Validator
    description: APIs intended for validator clients
paths:

  /v1/beacon/genesis:
    $ref: "./apis/beacon/genesis.yaml"
  /v1/beacon/states/{state_id}/root:
    $ref: "./apis/beacon/states/root.yaml"
  /v1/beacon/states/{state_id}/fork:
    $ref: "./apis/beacon/states/fork.yaml"
  /v1/beacon/states/{state_id}/finality_checkpoints:
    $ref: "./apis/beacon/states/finality_checkpoints.yaml"
  /v1/beacon/states/{state_id}/validators:
    $ref: "./apis/beacon/states/validators.yaml"
  /v1/beacon/states/{state_id}/validators/{validator_id}:
    $ref: "./apis/beacon/states/validator.yaml"
  /v1/beacon/states/{state_id}/committees/{epoch}:
    $ref: "./apis/beacon/states/committee.yaml"
  /v1/beacon/headers:
    $ref: "./apis/beacon/blocks/headers.yaml"

  /v1/node/identity:
    $ref: "./apis/node/identity.yaml"
  /v1/node/peers:
    $ref: "./apis/node/peers.yaml"
  /v1/node/peers/{peer_id}:
    $ref: "./apis/node/peer.yaml"
  /v1/node/version:
    $ref: "./apis/node/version.yaml"
  /v1/node/syncing:
    $ref: "./apis/node/syncing.yaml"
  /v1/node/health:
    $ref: "./apis/node/health.yaml"

  /validator/duties/{epoch}/attester:
    $ref: "./apis/validator/duties.yaml#/attester"
  /validator/duties/{epoch}/proposer:
    $ref: "./apis/validator/duties.yaml#/proposer"
  /validator/beacon_committee_subscriptions:
    $ref: "./apis/validator/beacon_committee_subscriptions.yaml#/create"
  /validator/beacon_committee_subscription/{committee_index}/attestations:
    $ref: "./apis/validator/beacon_committee_subscriptions.yaml#/attestations"
  /validator/aggregate_and_proof:
    $ref: "./apis/validator/aggregate_and_proof.yaml"
  /validator/attestation:
    $ref: "./apis/validator/attestation.yaml"
  /validator/block:
    $ref: "./apis/validator/block.yaml"

components:
  schemas:
    BeaconBlock:
      $ref: './types/block.yaml#/schemas/BeaconBlock'
    SignedBeaconBlock:
      $ref: './types/block.yaml#/schemas/SignedBeaconBlock'
    SignedBeaconBlockHeader:
      $ref: './types/block.yaml#/schemas/SignedBeaconBlockHeader'
    ValidatorResponse:
      $ref: './types/api.yaml#/ValidatorResponse'
    ValidatorStatus:
      $ref: './types/api.yaml#/ValidatorStatus'
    Committee:
      $ref: './types/api.yaml#/Committee'
    AttesterDuty:
      $ref: './types/validator.yaml#/AttesterDuty'
    SignedAggregateAndProof:
      $ref: './types/validator.yaml#/SignedAggregateAndProof'
    Attestation:
      $ref: './types/attestation.yaml#/schemas/Attestation'
    Fork:
      $ref: './types/misc.yaml#/schemas/Fork'
    Checkpoint:
      $ref: './types/misc.yaml#/schemas/Checkpoint'
    PublicKey:
      $ref: './types/primitive.yaml#/schemas/PublicKey'
    Uint64:
      $ref: './types/primitive.yaml#/schemas/Uint64'
    NetworkIdentity:
      $ref: './types/p2p.yaml#/NetworkIdentity'
    Peer:
      $ref: './types/p2p.yaml#/Peer'
    PeerId:
      $ref: './types/p2p.yaml#/PeerId'
    GenesisTime:
      $ref: './types/primitive.yaml#/schemas/GenesisTime'
    Version:
      $ref: './types/primitive.yaml#/schemas/Version'
    ForkVersion:
      $ref: './types/primitive.yaml#/schemas/ForkVersion'
    Root:
      $ref: './types/primitive.yaml#/schemas/Root'
    Hex:
      $ref: './types/primitive.yaml#/schemas/Root'
    Signature:
      $ref: './types/primitive.yaml#/schemas/Signature'

  parameters:
    StateId:
      $ref: './params/index.yaml#/StateId'

  responses:
    InvalidRequest:
      $ref: './types/http.yaml#/InvalidRequest'
    InternalError:
      $ref: './types/http.yaml#/InternalError'
    NotFound:
      $ref: './types/http.yaml#/NotFound'
    CurrentlySyncing:
      $ref: './types/http.yaml#/CurrentlySyncing'
