get:
  operationId: getDepositContract
  summary: Get deposit contract address.
  description: Retrieve Eth1 deposit contract address and chain ID.
  tags:
    - Config
  responses:
    "200":
      description: Success
      content:
        application/json:
          schema:
            title: GetDepositContractResponse
            type: object
            properties:
              data:
                type: object
                properties:
                  chain_id:
                    allOf:
                      - $ref: ../../beacon-node-oapi.yaml#/components/schemas/Uint64
                      - description: Id of Eth1 chain on which contract is deployed.
                      - example: "1"
                  address:
                    allOf:
                      - $ref: ../../beacon-node-oapi.yaml#/components/schemas/Hex
                      - description: Hex encoded deposit contract address with 0x prefix
                      - example: "0x1Db3439a222C519ab44bb1144fC28167b4Fa6EE6"
    "500":
      $ref: ../../beacon-node-oapi.yaml#/components/responses/InternalError
