name: Spellcheck

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rojopolis/spellcheck-github-actions@0.40.0
        name: Spellcheck
